# Generated by Django 4.2.11 on 2024-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("vulnerability_type", models.CharField(max_length=100)),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
