# Generated by Django 4.2.11 on 2024-04-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanresult",
            name="scan_date",
        ),
        migrations.AddField(
            model_name="scanresult",
            name="endpoint",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="mitigation",
            field=models.TextField(default="No mitigations provided"),
        ),
    ]
