# Generated by Django 4.2.11 on 2024-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_remove_scanresult_scan_date_scanresult_endpoint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanresult",
            name="endpoint",
        ),
        migrations.AddField(
            model_name="scanresult",
            name="details",
            field=models.TextField(default="N/A"),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="mitigation",
            field=models.TextField(),
        ),
    ]
