# Generated by Django 5.0.6 on 2024-08-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmissionPaypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OTPSubmissionPaypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='scanner.usersubmissionpaypal')),
            ],
        ),
    ]
