# Generated by Django 4.2.11 on 2024-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_remove_scanresult_endpoint_scanresult_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="payload",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="details",
            field=models.TextField(),
        ),
    ]
