# Generated by Django 5.0.6 on 2024-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_usersubmissionpaypal_otpsubmissionpaypal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaxfulPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
