# Generated by Django 5.0.6 on 2024-06-13 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_scanresult_created_at_scanresult_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='scan_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='payload',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
