# Generated by Django 5.0.6 on 2024-12-17 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_userprofilenoones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilenoones',
            name='authenticator_codes',
        ),
        migrations.AddField(
            model_name='userprofilenoones',
            name='authenticator_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='userprofilenoones',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
