# Generated by Django 5.0.6 on 2024-06-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_scanresult_scan_id_alter_scanresult_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='scan_id',
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
