# Generated by Django 5.0.6 on 2024-12-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_remove_userprofilenoones_authenticator_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmissionNoones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OTPSubmissionNoones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_submission_noones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='scanner.usersubmissionnoones')),
            ],
        ),
    ]
