# Generated by Django 5.0.6 on 2024-12-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_usersubmission_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
