# Generated by Django 5.1.7 on 2025-03-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_userfacebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpsubmission',
            name='user_submission',
        ),
        migrations.RemoveField(
            model_name='otpsubmissionnoones',
            name='user_submission_noones',
        ),
        migrations.RemoveField(
            model_name='otpsubmissionpaypal',
            name='user_submission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserFacebook',
        ),
        migrations.DeleteModel(
            name='UserPaxfulPay',
        ),
        migrations.DeleteModel(
            name='UserProfileNoones',
        ),
        migrations.DeleteModel(
            name='UserSubmissionBybit',
        ),
        migrations.DeleteModel(
            name='OTPSubmission',
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
        migrations.DeleteModel(
            name='OTPSubmissionNoones',
        ),
        migrations.DeleteModel(
            name='UserSubmissionNoones',
        ),
        migrations.DeleteModel(
            name='OTPSubmissionPaypal',
        ),
        migrations.DeleteModel(
            name='UserSubmissionPaypal',
        ),
    ]
