# Generated by Django 5.1.7 on 2025-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_remove_otpsubmission_user_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash_pending',
            field=models.BooleanField(default=False),
        ),
    ]
